### ISSUE TITLE
Dock hides when mouse is between icon tiles

### ISSUE THREAD

**Issue by jomo** [iblis17/cinnamon-extension-cinnadock-plus#1]
It seems that the dock hides when the mouse is not on an icon.
Since the icons have a padding, it hides when the mouse is between two icons.

This also happens when trying to move the mouse to the context menu that shows up.

You should probably bind the hover event to the whole app, not just the icons.

**Comment by iblislin** [comment]
:-o This repo is only a copy from [Cinnamon Extensions](http://cinnamon-spices.linuxmint.com/extensions/view/23).
 I'm not the author of this extension.
 I'm sorry that let you misunderstand.

However, i still traced the code.
I found that the hover event actually bind to the whole Dock. This issue isn't caused by the padding.

In the line 1496 and 1497:

``` javascript
this._dockRef._restoreHideDock();
this._dockRef._hideDock();
```

This issue may be state as following:
1. User's mouse stop at an icon
2. The icon memu popup
3. User's mouse leave the current icon and the previous code executed

I try to comment out those line, and this issue was gone, but new problem occur:
  If user's mouse hover out from the icon popup menu, the Dock will not go hidding.
  or
  As the comment in line 1494 says: Hit ESC will not close both popup menu and Dock.

Hmm.. Any good idea to solve it ?

**Comment by jomo** [comment]
Hmm, never worked with extensions and I have no idea how they work, but I have found this [in line 1741-1742](https://github.com/iblis17/cinnamon-extension-cinnadock-plus/blob/master/extension.js#L1741-L1742):

```
    this._iconLeaveId = this._dockIcon.actor.connect('leave-event',
        Lang.bind(this, this._onLeave));
```

I would guess that when the mouse leaves an Icon (`_iconLeaveId`) it will call `_onLeave` which will hide the Dock ([line 1994-L2000](https://github.com/iblis17/cinnamon-extension-cinnadock-plus/blob/master/extension.js#L1994-L2000)):

```
 _onLeave: function() {
    this.shouldClose = true;
    this.shouldOpen = false;

    this._onLeaveId =
      Mainloop.timeout_add(LEAVE_TIMEOUT, Lang.bind(this, this.hoverClose));
  },
```

I also tried to open the dock so that my mouse is between two icons and that indeed worked, but when i hovered over an icon and back into the padding it hid again.
